version: "3.0"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sample_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: --port 3306
    tty: true
  api:
    depends_on:
      - db
    build: ./backend
    volumes:
      - ./backend/app:/code/app:cached
    ports:
      - 8000:8000
  client:
    build: ./frontend
    volumes: 
      - ./frontend:/app:cached
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    tty: true
    ports:
      - 8080:8080
    command: pnpm run dev
  
